#!/usr/bin/env python3
"""Translate Klaus Dormann's as65-syntax test sources to ca65.

Covers what 6502_interrupt_test.a65 uses: column-0 labels, `equ`/`=`,
`macro name [param]` … `endm` with `\\1` or named parameters, `if/else/endif`
(`!=` → `<>`), `org` (each block becomes a segment "O_xxxx" with a linker
config generated alongside), `db/dw/ds`, `noopt`/`end`/`bss`/`code`/`data`
(dropped), and the `report = 1` blocks (dropped: they need report.i65).
`wai`/`stp` byte macros are dropped in favour of the native mnemonics, and
every `success` expansion gets a `success_N` label for the harness.

    as65_to_ca65.py <in.a65> <out.s> <out.cfg>
"""
import re, sys

src, out_s, out_cfg = sys.argv[1:4]
lines = open(src, encoding="latin-1").read().splitlines()
out, orgs = [], []
macro_params = {}
in_macro = None
skip_depth = None          # inside `if report = 1` … endif
depth = 0
success_n = 0
seg_n = 0

def fix_expr(e):
    e = e.replace("!=", "<>")
    e = re.sub(r"\(1<<IRQ_bit\|1<<NMI_bit\)", "((1<<IRQ_bit)|(1<<NMI_bit))", e)
    return e

out.append('; Generated by tools/as65_to_ca65.py from %s — do not edit.\n.p816\n.a8\n.i8\n' % src.split('/')[-1])
for raw in lines:
    line = raw.rstrip()
    code, _, comment = line.partition(";")
    if not code.strip():
        out.append(line); continue
    m = re.match(r"^(\S+)?\s*(\S+)?\s*(.*)$", code)
    label = m.group(1) if code[0] not in " \t" else None
    rest = code[len(label):].strip() if label else code.strip()
    toks = rest.split(None, 1)
    op = toks[0].lower() if toks else ""
    arg = toks[1].strip() if len(toks) > 1 else ""
    # drop report=1 blocks entirely
    if skip_depth is not None:
        if op == "if": depth += 1
        elif op == "endif":
            depth -= 1
            if depth <= skip_depth: skip_depth = None
        continue
    if op == "if" and re.search(r"\breport\s*=\s*1\b", arg):
        skip_depth = depth; depth += 1; continue
    if op == "if": depth += 1
    if op == "endif": depth -= 1
    # macro definitions
    if op == "macro":
        name = label; params = [p.strip() for p in arg.split(",")] if arg else []
        if name in ("wai", "stp"): in_macro = "DROP"; continue
        in_macro = name
        macro_params[name] = params
        out.append(".macro %s%s" % (name, (" " + ", ".join(params)) if params else " p1"))
        continue
    if op == "endm":
        if in_macro != "DROP": out.append(".endmacro")
        in_macro = None; continue
    if in_macro == "DROP": continue
    # directives
    if op in ("noopt", "end", "bss", "code", "data"): continue
    if op == "org":
        seg = "O_%d" % seg_n; seg_n += 1
        orgs.append((seg, fix_expr(arg)))
        out.append('.segment "%s"' % seg); continue
    if label and op in ("equ", "="):
        out.append("%s = %s" % (label, fix_expr(arg))); continue
    if label and op == "ds":
        out.append("%s: .res %s" % (label, fix_expr(arg))); continue
    if label and op == "":
        out.append("%s:" % label); continue
    prefix = ("%s: " % label) if label else "        "
    if op == "ds": out.append(prefix + ".res " + fix_expr(arg)); continue
    if op == "db": out.append(prefix + ".byte " + fix_expr(arg)); continue
    if op == "dw": out.append(prefix + ".word " + fix_expr(arg)); continue
    if op in ("if", "else", "endif"):
        out.append(prefix + "." + op + ((" " + fix_expr(arg)) if arg else "")); continue
    if op == "success":
        out.append("success_%d:" % success_n); success_n += 1
        out.append(prefix + "success"); continue
    # macro body: \1 → first param name
    text = rest
    if in_macro and in_macro in macro_params:
        params = macro_params[in_macro] or ["p1"]
        text = text.replace("\\1", params[0])
    out.append(prefix + fix_expr(text) + (("  ;" + comment) if comment else ""))

# ld65 -Ln lists exported symbols only: export every code/data label.
labels = []
for l in out:
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):", l)
    if m: labels.append(m.group(1))
for name in labels:                      # labels inside a false .if are never defined
    out.append(".ifdef %s\n.export %s\n.endif" % (name, name))
open(out_s, "w").write("\n".join(out) + "\n")
cfg = ["MEMORY {", "    RAM: start = $0000, size = $10000, file = %O, fill = yes, fillval = $00;", "}", "SEGMENTS {"]
for seg, start in orgs:
    cfg.append("    %s: load = RAM, start = %s;" % (seg, start.replace("zero_page", "$0A").replace("data_segment", "$200").replace("code_segment", "$400")))
cfg.append("}")
open(out_cfg, "w").write("\n".join(cfg) + "\n")
print("translated %d lines, %d org blocks, %d success traps" % (len(lines), len(orgs), success_n))
